#! /usr/bin/env bash

os="$(uname -s)"


# global
alias ..='cd ..'
alias ...='cd ../..'
alias c='clear'
alias e='printf "\e[2J\e[3J\e[1;1H'
[[ -x /usr/local/bin/gdu ]] && alias du='gdu'
alias sizeof='du -s --apparent-size --si'
alias mpv='mpv --no-audio-display'


## ls
if [[ "$os" == "Darwin" ]]; then
	[[ -x /usr/local/bin/gls ]] && alias ls='gls --color=tty'
elif [[ "$os" == "Linux" ]]; then
	alias ls='ls --color=tty'
fi
alias l='ls -alhF'
alias ll='ls -lhF'
alias lsa='ls -alhF'
alias lst='ls -trlhF'


## don't save history on exit
alias nohist='export HISTFILE=/dev/null'


## make various things interactive
if [[ "$os" == "Darwin" ]]; then
	# use APFS copy-on-write
	alias cp='cp -aic'
else
	alias cp='cp -ai'
fi
alias ln='ln -i'
alias mv='mv -i'


# some os-specific settings

if [[ "$os" == "Darwin" ]]; then
	alias brwe='brew'
	[[ -x /usr/local/bin/colordiff ]] && alias diff='colordiff'
	alias ext4fuse='sudo ext4fuse -o allow_other'
	[[ -x /usr/local/bin/trash ]] && alias rm='trash'
fi

if [[ "$os" == "Linux" ]]; then
	[[ -x /usr/bin/batcat ]] && alias bat='batcat'
	alias open='xdg-open'
fi

