#! /usr/bin/env bash

os="$(uname -s)"

# global
alias ..='cd ..'
alias ...='cd ../..'
alias c='clear'
alias e='printf "\e[2J\e[3J\e[1;1H"'
[[ -x /usr/local/bin/gdu ]] && alias du='/usr/local/bin/gdu'
alias sizeof='du -s --apparent-size --si'
alias mpv='mpv --no-audio-display'
alias ffmpeg="ffmpeg -hide_banner"
alias ffprobe="ffprobe -hide_banner"
alias rsync="rsync -ah --info=progress2 --stats --filter=':- .gitignore'"
alias z="SHELL=zsh exec zsh -l"
alias make="make -j$(nproc)"
alias dua="dua --format metric"
alias intelwatt="sudo intel_gpu_top -J | grep -o -P '(?<=Package\": )\d+\.\d'"

## ls
if [[ "$os" == "Darwin" ]]; then
    [[ -x /usr/local/bin/gls ]] && alias ls='gls --color=auto'
    [[ -x /opt/homebrew/bin/gls ]] && alias ls='gls --color=auto'
else
    alias ls='ls --color=auto'
fi
alias l='ls -lhF'
alias ll='ls -alhF'
alias lsa='ls -alhF'
alias lst='ls -trlhF'

# https://github.com/sharkdp/fd/issues/1295
ff() {
    fd "$@" -X ls -1 --directory --indicator-style=slash --hyperlink
}

## don't save history on exit
alias nohist='export HISTFILE=/dev/null'
alias n="nohist"


## make various things interactive
if [[ "$os" == "Darwin" ]]; then
    # use APFS copy-on-write
    alias cp='cp -aic'
else
    alias cp='cp -ai'
fi
alias ln='ln -i'
alias mv='mv -i'


# some os-specific settings

if [[ "$os" == "Darwin" ]]; then
    alias brwe='brew'
    alias ext4fuse='sudo ext4fuse -o allow_other'
    alias sshfs='sudo sshfs -o allow_other,default_permissions,uid=501,gid=20'
    [[ -x /usr/local/bin/gstat ]] && alias stat='gstat'
fi

# copy some aliases from zsh git completions to bash
alias ga='git add'
alias gco='git checkout'
alias gcl='git clone --recurse-submodules'
alias gc='git commit --verbose'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gfa='git fetch --all'
alias gl='git pull'
alias gp='git push'
alias grb='git rebase'
alias grs='git restore'
alias gsh='git show'
alias gst='git status'
alias gsw='git switch'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias wglog='watch --color --interval 1 git log --color=always --oneline --decorate --graph'
alias wgloga='watch --color --interval 1 git log --color=always --oneline --decorate --graph --all'
