#! /usr/bin/env bash

os="$(uname -s)"
utlab=false
[[ -x /usr/local/bin/cshosts ]] && utlab=true

# global
alias ..='cd ..'
alias ...='cd ../..'
alias c='clear'
alias e='printf "\e[2J\e[3J\e[1;1H"'
[[ -x /usr/local/bin/gdu ]] && alias du='/usr/local/bin/gdu'
alias sizeof='du -s --apparent-size --si'
alias mpv='mpv --no-audio-display'
alias ffmpeg="ffmpeg -hide_banner"
alias ffprobe="ffprobe -hide_banner"
alias rsync="rsync --filter=':- .gitignore'"
alias z="SHELL=zsh exec zsh -l"

## ls
if [[ "$os" == "Darwin" ]]; then
    [[ -x /usr/local/bin/gls ]] && alias ls='gls --color=tty'
elif [[ "$os" == "Linux" ]]; then
    alias ls='ls --color=tty'
fi
alias l='ls -alhF'
alias ll='ls -lhF'
alias lsa='ls -alhF'
alias lst='ls -trlhF'


## don't save history on exit
alias nohist='export HISTFILE=/dev/null'


## make various things interactive
if [[ "$os" == "Darwin" ]]; then
    # use APFS copy-on-write
    alias cp='cp -aic'
else
    alias cp='cp -ai'
fi
alias ln='ln -i'
alias mv='mv -i'


# some os-specific settings

if [[ "$os" == "Darwin" ]]; then
    alias brwe='brew'
    [[ -x /usr/local/bin/colordiff ]] && alias diff='colordiff'
    alias ext4fuse='sudo ext4fuse -o allow_other'
    alias sshfs='sudo sshfs -o allow_other,default_permissions,uid=501,gid=20'
    [[ -x /usr/local/bin/gstat ]] && alias stat='gstat'
fi

if [[ "$os" == "Linux" ]]; then
    [[ -x /usr/bin/batcat ]] && alias bat='batcat'
    alias open='xdg-open'
fi

# copy some aliases from zsh git completions to bash
if [[ "$(echo $SHELL)" =~ .*/bash ]]; then
    alias gst='git status'
    alias ga='git add'
    alias gd='git diff'
    alias gds='git diff --staged'
    alias gc='git commit -v'
    alias gf='git fetch'
    alias gl='git pull'
    alias gp='git push'
    alias glog='git log --oneline --decorate --graph'
    alias gloga='git log --oneline --decorate --graph --all'
    alias gsw='git switch'
fi
